# version del lenguaje que voy a usar
version: "3.8"

#Estructura services, networks, volumes.
#services:
#networks:
#volumes:
services:
  # database engine service
  postgres_db:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    volumes:
      #allow *.sql, *.sql.gz, or *.sh and execute only if data directory is empty.
      # - postgres_data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Monta el script de inicialización
      - ./dbfiles:/docker-entrypoint-initdb.d
      - ./postgres_data:/var/lib/postgresql/data
  # database admin service
  adminer:
    image: adminer:latest
    ports:
      - "9080:8080"
    depends_on:
      - postgres_db

  # Billing app backend
  billingapp-back:
    build:
      context: ./java
      args:
        - JAR_FILE=*.jar
        - DB_PASSWORD=qwerty
    container_name: billingApp-back
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
    depends_on:
      - postgres_db
    ports:
      - 8080:8080

  # Billing app backend
  billingapp-front:
    build:
      context: ./angular
    container_name: billingApp-front
    depends_on:
      - billingapp-back
    ports:
      - 80:80

volumes:
  postgres_data:
    external: false
